version: 1.54.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: $(appveyor_repo_commit)
before_build:
  - cmd: git submodule update --init --recursive
  - cmd: dotnet --version
  - cmd: dotnet restore OverwatchToolchain.sln --verbosity m
build_script:
  - cmd: dotnet build --configuration Release
  - cmd: dotnet build --configuration Debug
branches:
  only:
    - masterz
artifacts:
  - path: DataTool/bin/Release/net5.0-windows
    name: toolchain-release
  - path: DataTool/bin/Debug/net5.0-windows
    name: toolchain-debug
  - path: TankView/bin/Release/net5.0-windows
    name: TankView-release
  - path: TankView/bin/Debug/net5.0-windows
    name: TankView-debug
  - path: TACTLib/TACTLib/bin/Release/net5.0/TACTLib.dll
    name: TACTLib
  - path: TankLib/bin/Release/net5.0-windows/TankLib.dll
    name: TankLib
test: false
deploy: false
cache:
  - packages -> **\packages.config 
