version: 1.54.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{build}'
before_build:
  - cmd: git submodule update --init --recursive
  - cmd: dotnet --version
  - cmd: dotnet restore OverwatchToolchain.sln --verbosity m
build_script:
  - cmd: dotnet publish --configuration Release /p:PublishTrimmed=false --self-contained false -o dist/Release
  - cmd: dotnet publish --configuration Debug /p:PublishTrimmed=false --self-contained false -o dist/Debug
branches:
  only:
    - master
after_build:
  - cmd: copy /B /Y dist\Release\runtimes\win-x64\native\*.dll dist\Release\x64
  - cmd: del /S /Q dist\Release\runtimes\win-x86 dist\Release\x86
  - cmd: rmdir /S /Q dist\Release\runtimes\win-x86 dist\Release\x86
  - cmd: copy /B /Y dist\Debug\runtimes\win-x64\native\*.dll dist\Debug\x64
  - cmd: del /S /Q dist\Debug\runtimes\win-x86 dist\Debug\x86
  - cmd: rmdir /S /Q dist\Debug\runtimes\win-x86 dist\Debug\x86
artifacts:
- path: dist/Release
  name: toolchain-release
- path: dist/Debug
  name: toolchain-debug
test: false
deploy: false
cache:
  - packages -> **\packages.config 
