version: 1.54.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: $(appveyor_repo_commit)
before_build:
  - cmd: git submodule update --init --recursive
  - cmd: dotnet --version
  - cmd: dotnet restore OverwatchToolchain.sln --verbosity m
build_script:
  - cmd: dotnet publish --configuration Release /p:PublishTrimmed=false --self-contained false -o dist/Release
  - cmd: dotnet publish --configuration Debug /p:PublishTrimmed=false --self-contained false -o dist/Debug
  - cmd: dotnet publish --configuration Release /p:PublishTrimmed=false --self-contained true -o dist/SelfContained
branches:
  only:
    - master
after_build:
  - cmd: copy /B /Y dist\Release\DirectXTexNetImpl.dll dist\Release\x64
  - cmd: copy /B /Y dist\Debug\DirectXTexNetImpl.dll dist\Debug\x64
  - cmd: copy /B /Y dist\SelfContained\DirectXTexNetImpl.dll dist\SelfContained\x64
artifacts:
  - path: dist/Release
    name: toolchain-release
  - path: dist/Debug
    name: toolchain-debug
  - path: dist/SelfContained
    name: toolchain-selfcontained
test: false
deploy: false
